export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ALL_DOCUMENTS = 'GET_ALL_DOCUMENTS';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const GET_ALL_USERS = 'GET_ALL_USERS';
