export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ALL_DOCUMENTS = 'GET_ALL_DOCUMENTS';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_PROFILE = 'GET_PROFILE';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const EDIT_USER_ROLE = 'EDIT_USER_ROLE';


